# python STDA_hp_cls_const_fbnm_with_grad.py --gpu_id 2 --s 1 --t 0 --max_epoch 30 --interval 30 --batch_size 64 --dset office-home --net deit_s --wandb 1 --fbnm_par 4.0 --grad_norm 1 --output_src src_train --output temp/STDA_wt_fbnm_workgrad_rlcc_soft_stg --suffix fbnm_workgrad_rlcc_soft_stg --rlcc --soft_pl
# python STDA_hp_cls_const_fbnm_with_grad.py --gpu_id 2 --s 1 --t 2 --max_epoch 30 --interval 30 --batch_size 64 --dset office-home --net deit_s --wandb 1 --fbnm_par 4.0 --grad_norm 1 --output_src src_train --output temp/STDA_wt_fbnm_workgrad_rlcc_soft_stg --suffix fbnm_workgrad_rlcc_soft_stg --rlcc --soft_pl
# python STDA_hp_cls_const_fbnm_with_grad.py --gpu_id 2 --s 1 --t 3 --max_epoch 30 --interval 30 --batch_size 64 --dset office-home --net deit_s --wandb 1 --fbnm_par 4.0 --grad_norm 1 --output_src src_train --output temp/STDA_wt_fbnm_workgrad_rlcc_soft_stg --suffix fbnm_workgrad_rlcc_soft_stg --rlcc --soft_pl

# python MTDA_all_data.py --gpu_id 0 --s 1 --t 0 --max_epoch 30 --interval 300 --batch_size 56 --dset office-home --net deit_s --wandb 1 --fbnm_par 4.0 --grad_norm 1 --output_src src_train --output temp/STDA_wt_fbnm_workgrad_rlcc_soft_stg --suffix MTDA --rlcc --soft_pl
# python MTDA_all_data.py --gpu_id 1 --s 0 --max_epoch 30 --interval 300 --batch_size 56 --dset office-home --net deit_s --wandb 1 --fbnm_par 4.0 --grad_norm 1 --output_src src_train --output temp/STDA_wt_fbnm_workgrad_rlcc_soft_stg --suffix MTDA --rlcc --soft_pl
# python3 STDA_im.py --batch_size 56 --dset office-home --net deit_s --gpu_id 0 --max_epoch 50 --interval 50 --s 0 --t 0 1 --wandb 1 --output_src src_train --output temp/deit/abla/STDA_wt_abla_im_ent --suffix abla_im_ent
# python3 STDA_im.py --batch_size 56 --dset office-home --net deit_s --gpu_id 1 --max_epoch 50 --interval 50 --s 0 --t 1 --wandb 1 --rlcc 1 --soft_pl 1 --output_src src_train --output temp/deit/abla/STDA_wt_abla_im_ent_rlccsoft --suffix abla_im_ent_rlccsoft
# python STDA_fbnm.py --s 0 --t 1 --max_epoch 50 --interval 50 --batch_size 56 --dset office-home --net deit_s --wandb 0 --fbnm_par 4.0 --output_src src_train --output temp/deit/abla/STDA_wt_fbnm --suffix abla_fbnm

python STDA_fbnm.py --gpu_id 2 --s 2 --t 0 1 --max_epoch 50 --interval 50 --batch_size 56 --dset office --net deit_s --wandb 1 --fbnm_par 4.0 --output_src src_train --output temp/deit/STDA_wt_fbnm_rlccsoft_ep50 --suffix fbnm_rlccsoft_ep50 --rlcc 1 --soft_pl 1
# python STDA_fbnm.py --gpu_id 2 --s 3 --t 0 1 2 --max_epoch 50 --interval 50 --batch_size 56 --dset office-home --net deit_s --wandb 1 --fbnm_par 4.0 --output_src src_train --output temp/deit/STDA_wt_fbnm_rlccsoft_ep50 --suffix fbnm_rlccsoft_ep50 --rlcc 1 --soft_pl 1
